name: Validate Homey App
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  main:
    name: Validate Homey App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: node -e "fs.writeFileSync('app.json', '{}');"
      - run: npm install -g homey
      - run: npm install
      - run: homey app validate --level publish
